In [3]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
a=np.array([])
b=np.array([1,2,3,45,0])
c=np.array([[12,3,4],[4,5,8]])

In [7]:
a

array([], dtype=float64)

In [8]:
b

array([ 1,  2,  3, 45,  0])

In [9]:
c

array([[12,  3,  4],
       [ 4,  5,  8]])

In [10]:
type(b)

numpy.ndarray

In [11]:
type(a)

numpy.ndarray

In [13]:
a.size

0

In [14]:
b

array([ 1,  2,  3, 45,  0])

In [15]:
b.ndim

1

In [16]:
b.size

5

In [17]:
c

array([[12,  3,  4],
       [ 4,  5,  8]])

In [18]:
c.ndim

2

In [19]:
c.size

6

In [20]:
c.shape

(2, 3)

In [21]:
type(c)

numpy.ndarray

In [22]:
c.ndim

2

In [25]:
n=np.array([[2,3,4,5], [20,10,40,30], [200,100,600,700]])

In [26]:
n.shape

(3, 4)

In [34]:
import numpy as np

In [37]:
n=np.array([[1,5,6,3],[7,4,8,9],[4,1,2,7]])

In [41]:
n

array([[1, 5, 6, 3],
       [7, 4, 8, 9],
       [4, 1, 2, 7]])

In [39]:
n[0,1:3]

array([5, 6])

In [40]:
n[1,2]

8

In [42]:
n[1:,2:]

array([[8, 9],
       [2, 7]])

In [43]:
n[1:3,2:4]

array([[8, 9],
       [2, 7]])

In [44]:
#SYNTAX = n[row,col]

In [45]:
n.shape

(3, 4)

In [62]:
n

array([[1, 5, 6, 3],
       [7, 4, 8, 9],
       [4, 1, 2, 7]])

In [48]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
np.sqrt(81)

9.0

In [50]:
n.max()

9

In [52]:
n.argmax()

7

In [53]:
np.random.rand(2,2)

array([[0.48945074, 0.06085148],
       [0.71540995, 0.8208104 ]])

In [55]:
np.random.randn(2,2)

array([[ 0.18223843, -0.64315672],
       [-0.93105244, -1.44665544]])

In [59]:
np.random.randint(9,90,12).reshape(6,2)

array([[34, 55],
       [84, 88],
       [ 9, 17],
       [80, 27],
       [32, 58],
       [14, 39]])

In [66]:
d = np.array([[4,40][5,50][6,60]] , [[7,70],[8,80][]9,90]] ,[[5,55][4,40],[6,60]]])

SyntaxError: invalid syntax (2359485899.py, line 1)

In [64]:
d.shape

NameError: name 'd' is not defined